---

meta: (( merge ))
name: (( merge ))
director_uuid: (( merge ))

releases:
- {name: geode, version: latest}

networks:
- name: default
  subnets: (( merge ))

resource_pools:
- name: geode-locators
  network: default
  stemcell: (( meta.stemcell ))
  cloud_properties: 
    <<: (( merge ))

- name: geode-cacheservers
  network: default
  stemcell: (( meta.stemcell ))
  cloud_properties: 
    <<: (( merge ))

compilation:
  workers: 2
  network: default
  cloud_properties: (( merge ))

update:
  canaries: 1
  max_in_flight: 10
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
  serial: false

jobs:
- name: geode-locator
  instances: (( merge ))
  templates:
  - {name: locator, release: geode}
  consumes:
    locator: {from: geode-locator}
  provides:
    discovery: {as: geode-locator}
  persistent_disk: 10_240
  resource_pool: geode-locators
  networks:
  - name: default

- name: geode-cacheserver
  instances: (( merge ))
  templates:
  - {name: cacheserver, release: geode}
  consumes:
    locator: {from: geode-locator}
  persistent_disk: 10_240
  resource_pool: geode-cacheservers
  networks:
  - name: default

